listen              1935;
max_connections     1000;
daemon              off;
srs_log_tank        console;

http_api {
    enabled         on;
    listen          1985;
}

http_server {
    enabled         on;
    listen          8080;
    dir             ./objs/nginx/html;

    http_remux {
        enabled     on;
        mount       [vhost]/[app]/[stream].flv;
    }
}

vhost __defaultVhost__ {
    http_remux {
        enabled     on;
        mount       [vhost]/[app]/[stream].flv;
    }

    hls {
        enabled     on;
        hls_path    ./objs/nginx/html;
        hls_fragment 5;
        hls_window  30;
    }

    http_hooks {
        enabled         on;
        on_publish      http://backend:8080/api/live/srs/on_publish;
        on_unpublish    http://backend:8080/api/live/srs/on_unpublish;
    }
}
